INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (7, 1, 'In Stock');
INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (8, 1, 'Pre-Order');
INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (5, 1, 'Out Of Stock');
INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (6, 1, '2-3 Days');
INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (7, 2, 'In Stock');
INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (8, 2, 'Pre-Order');
INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (5, 2, 'Out Of Stock');
INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (6, 2, '2-3 Days');
INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (7, 3, 'In Stock');
INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (8, 3, 'Pre-Order');
INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (5, 3, 'Out Of Stock');
INSERT INTO `oc_stock_status` (`stock_status_id`, `language_id`, `name`) VALUES (6, 3, '2-3 Days');
