INSERT INTO `oc_toc_doproskin` (`skin_id`, `skinname`, `inbox`, `custom_css`, `status`) VALUES (1, 'luxury', 1, '', 1);
INSERT INTO `oc_toc_doproskin` (`skin_id`, `skinname`, `inbox`, `custom_css`, `status`) VALUES (2, 'red-black', 0, '', 0);
INSERT INTO `oc_toc_doproskin` (`skin_id`, `skinname`, `inbox`, `custom_css`, `status`) VALUES (3, 'deepblue', 0, '', 0);
INSERT INTO `oc_toc_doproskin` (`skin_id`, `skinname`, `inbox`, `custom_css`, `status`) VALUES (4, 'wood', 0, '', 0);
INSERT INTO `oc_toc_doproskin` (`skin_id`, `skinname`, `inbox`, `custom_css`, `status`) VALUES (5, 'black', 0, '', 0);
INSERT INTO `oc_toc_doproskin` (`skin_id`, `skinname`, `inbox`, `custom_css`, `status`) VALUES (6, 'line', 0, '', 0);
INSERT INTO `oc_toc_doproskin` (`skin_id`, `skinname`, `inbox`, `custom_css`, `status`) VALUES (7, 'farbic', 0, '', 0);
INSERT INTO `oc_toc_doproskin` (`skin_id`, `skinname`, `inbox`, `custom_css`, `status`) VALUES (8, 'clean-blue', 0, ' .caption > h4 + p {display:none;}', 0);
INSERT INTO `oc_toc_doproskin` (`skin_id`, `skinname`, `inbox`, `custom_css`, `status`) VALUES (9, 'starry-night', 1, ' .caption > h4 + p {display:none;}', 0);
INSERT INTO `oc_toc_doproskin` (`skin_id`, `skinname`, `inbox`, `custom_css`, `status`) VALUES (10, 'creamy', 1, '', 0);
